# This is a basic workflow to help you get started with Actions

name: compile-project-and-deploy-to-gh-pages-branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout from master branch
        uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: Compile latex
        run: python3 ./build_html.py

#      - name: Install rsync
#        run: |
#          apt-get update && apt-get install -y rsync

      - name: deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
